### ISSUE TITLE
More concise syntax for default values

### ISSUE THREAD

**Issue by jonemo** [TadLeonard/enumap#1]
Currently, to specify the default value for a `SparseEnumap` field, this syntax is necessary:

```python
class AThing(SparseEnumap):
    a_field: int = auto()

AThing.set_defaults(a_field="a default value")
```

Taking inspiration from the new (as of Python 3.6.1) syntax for `typing.NamedTuple`, it would be nice to be able to write:

```python
class AThing(SparseEnumap):
    a_field: int = "a default value"
```

For reference, the example for `typing.NamedTuple` syntax in the Python docs is:

```python
class Employee(NamedTuple):
    """Represents an employee."""
    name: str
    id: int = 3

    def __repr__(self) -> str:
        return f'<Employee {self.name}, id={self.id}>'
```

**Comment by TadLeonard** [comment]
Fixed by #2
